[![GitHub Pages Deployment](https://github.com/dr-juetz-arzt/privatarzt-dr-martin-juetz/actions/workflows/static.yml/badge.svg?branch=main)](https://github.com/dr-juetz-arzt/privatarzt-dr-martin-juetz/actions/workflows/static.yml)
